name: Inspect Rules

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  inspect-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
      - run: npm run inspect-rules:check
